allowBuilds:
  '@percy/core': true
  cypress: true
  esbuild: true
  husky: true
overrides:
  eslint-plugin-react-hooks: ^7.1.1
onlyBuiltDependencies:
  - '@percy/core'
  - cypress
  - esbuild
  - husky
