name: Release

on: [push]


permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci') && github.repository == 'ValentinH/react-easy-crop'"
    steps:
      - uses: actions/checkout@v6

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: pnpm-deps-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-deps-${{ hashFiles('pnpm-lock.yaml') }}

      - run: pnpm install --frozen-lockfile

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx auto shipit
